server:
  port: 0

spring:
  cloud:
    config:
      profile: dev
  application:
    name: booking-microservice
  datasource:
      jmx-enabled: true
      password: root
      username: admin

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
