server:
  port: 0

spring:
  application:
    name: booking-microservice
  datasource:
      url: "jdbc:mysql://localhost/bookingdb"
      jmx-enabled: true
      password: root
      username: admin

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
