booking:
  property:
    Booking Profile Dev

spring:
  datasource:
    url: "jdbc:mysql://localhost/bookingdb"
    jmx-enabled: true
    password: root
    username: admin
  jpa:
    hibernate: 
      ddl-auto: update
      show-sql: true
      generate-ddl: true  
