spring:
  cloud:
    config:
      server:
        git:
          default-label: service-configuration
          uri: https://github.com/Raulcudris/MicroservicesJavaWhitMysqlAndMongodb.git
          search-paths: service-configuration
  application:
  name: config-server




